auth-server-url: ${AUTH_SERVER_URL}
mp:
  messaging:
    incoming:
      container-events:
        connector: smallrye-rabbitmq
        queue:
          name: container-events
        exchange:
          name: container-events
quarkus:
  datasource:
    db-kind: mysql
    username: ${DB_USER}
    password: ${DB_PWD}
    reactive:
      url: ${DB_URL}
  http:
    port: ${HTTP_PORT:8080}
  smallrye-openapi:
    path: /swagger
    info-version: 1.0.1
  swagger-ui:
    always-include: true
    path: /swagger-ui
rabbitmq-host:  ${RABBIT_HOST:}
rabbitmq-port: ${RABBIT_PORT:}
rabbitmq-username: ${RABBIT_USERNAME:}
rabbitmq-password: ${RABBIT_PASSWORD:}
